springfox:
  documentation:
    swagger-ui:
      enabled: true
      base-url: /documentation
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/easybuy?characterEncoding=UTF-8
    username: lzx
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: cn.boot.ymw.cn.pojo
  mapper-locations: classpath:/mapper/**/*.xml

